config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root 'welcome#index'

  get :test, to: 'welcome#test'
  get '/s/:slug', to: 'links#show', as: :short

  namespace :admin do
    get "login", to: "sessions#new"
    post "login", to: "sessions#create"
    get "register", to: "sessions#register"
    post "register", to: "sessions#signup"
    delete "logout", to: "sessions#destroy"

    get 'dashboard' => 'welcome#dashboard'

    resources :blogs do
      collection do
        post :upload
      end
      member do
        get :generate
      end
    end

  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blog.rb
class Blog < ApplicationRecord
  mount_uploader :file, FileUploader

  belongs_to :user
  LIMIT = 10

  validates :title, presence: true
  validates :description, presence: true
  validates :file, presence: true

  def self.generate_link(url)
    Link.shorten(url)
  end

end

app/models/link.rb
class Link < ApplicationRecord

  validates_presence_of :url
  validates :url, format: URI::regexp(%w[http https])
  validates_uniqueness_of :slug
  validates_length_of :url, within: 3..255, on: :create, message: "too long"
  validates_length_of :slug, within: 3..255, on: :create, message: "too long"

  # auto slug generation
  before_validation :generate_slug

  def generate_slug
    self.slug = SecureRandom.uuid[0..5] if self.slug.nil? || self.slug.empty?
    true
  end

  # fast access to the shortened link
  def short
    Rails.application.routes.url_helpers.short_url(slug: self.slug)
  end

  # the API
  def self.shorten(url, slug = '')
    link = Link.where(url: url, slug: slug).first
    return link.short if link

    link = Link.new(url: url, slug: slug)
    return link.short if link.save

    Link.shorten(url, slug + SecureRandom.uuid[0..2])
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :timeoutable

  has_many :blogs

end

app/controllers/admin/base_controller.rb
class Admin::BaseController < ApplicationController

end

app/controllers/admin/blogs_controller.rb
class Admin::BlogsController < Admin::BaseController

  before_action :authenticate_admin
  before_action :set_blog, only: [:edit, :update, :generate]

  def index
    @blogs = @current_user.blogs.page(params[:page]).per(Blog::LIMIT)
  end

  def new
    @blog = @current_user.blogs.new
  end

  def create
    @blog = @current_user.blogs.new(blog_params)
    if @blog.save
      flash[:success] = 'Successfully saved'
      redirect_to action: :index
    else
      render action: :new
    end
  end

  def edit

  end

  def update
    if @blog.update(blog_params.merge(shorturl: nil))
      flash[:success] = 'Successfully updated'
      redirect_to action: :index
    else
      render action: :edit
    end
  end

  def generate
    @blog.shorturl = Blog.generate_link("#{request.base_url}#{@blog.file}")
    if @blog.save
      flash[:success] = 'Successfully generated'
      redirect_to action: :index
    else
      flash[:error] = @blog.errors.messages
      render action: :index
    end
  end

  private

  def set_blog
    @blog = Blog.find params[:id]
  end

  def blog_params
    params.require(:blog).permit(:title,
                                 :file,
                                 :description)
  end

end

app/controllers/admin/sessions_controller.rb
class Admin::SessionsController < ApplicationController

  def new

  end

  def create
    if sign_in_admin
      redirect_to admin_dashboard_path
    else
      flash[:error] = 'Email/Password combination wrong, contact super admin.'
      render action: :new
    end
  end

  def register

  end

  def signup
    user = User.new(users_params)
    if user.save
      sign_in(user)
      flash[:success] = "Logged in successfully."
      redirect_to admin_dashboard_path
    else
      flash.now[:error] = "There was something wrong with your login details."
      render 'register'
    end
  end

  def destroy
    sign_out
    flash[:error] = "You have been logged out."
    redirect_to root_path
  end

  private

  def users_params
    params.require(:session).permit(:email,
                                    :password,
                                    :first_name,
                                    :last_name,
                                    :mobile,
                                    ).merge(role: 'admin')
  end

  def sign_in_admin
    email = params[:session][:email]
    password = params[:session][:password]
    return false unless email.present? or password.present?
    admin = User.where(email: email).first
    return false unless admin.present?
    if admin.valid_password?(password)
      flash[:success] = "Signed in as #{admin.email}. All admin operations are logged."
      sign_in(admin)
    end
  end

end

app/controllers/admin/welcome_controller.rb
class Admin::WelcomeController < ApplicationController
  before_action :authenticate_admin

  def dashboard

  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  skip_before_action :verify_authenticity_token

  def authenticate_admin
    if current_user.present?
      #proceed
    else
      redirect_to root_path
    end
  end
end

app/controllers/links_controller.rb
class LinksController < ApplicationController

  def show
    @link = Link.find_by_slug(params[:slug])
    render  file: "#{Rails.root}/public/404.html", status: 404, layout: false and return  if @link.nil?

    @link.update_attribute(:clicked, @link.clicked + 1)
    redirect_to @link.url
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  def index

  end

end

app/helpers/application_helper.rb
module ApplicationHelper

end

app/views/admin/blogs/_form.html.erb
<%= simple_form_for [:admin, @blog] do |f| %>
  <%= f.input :title %>
  <%= f.input :description %>
  <%= f.input :file, input_html: { class: 'form-control' }  %>
  <br>
  <%= f.submit 'Save', class: 'btn btn-outline-primary' %>
  <%= link_to 'List', admin_blogs_path, class: 'btn btn-outline-info' %>
<% end %>

app/views/admin/blogs/edit.html.erb
<div class="jumbotron">
  <h1 class="display-4">Edit Blog</h1>
</div>

<div class="row">
  <div class="col">
    <%= render partial: 'admin/blogs/form' %>
  </div>
  <div class="col"></div>
  <div class="col"></div>
</div>

app/views/admin/blogs/index.html.erb
<div class="jumbotron">
  <h1 class="display-4">Blogs</h1>
</div>
<div>
  <%= link_to 'New', new_admin_blog_path, class: 'btn btn-outline-primary float-end', role: "button" %>
</div>
<br>
<table class="table table-hover table-bordered">
  <thead>
  <tr class="table-primary">
    <th scope="col">Title</th>
    <th scope="col">Description</th>
    <th scope="col">Short link</th>
    <th scope="col">Original path</th>
    <th scope="col"></th>
  </tr>
  </thead>
  <tbody>
  <% @blogs.each do |f| %>
    <tr>
      <td><%= f.title %></td>
      <td><%= f.description %></td>
      <td>
        <% if f.shorturl %>
          <%= link_to f.shorturl, f.shorturl, target: '_blank' %>
          <% else %>
          <%= link_to "Generate", generate_admin_blog_path(f), target: '_blank' %>
          <% end %>
      </td>
      <td><%= link_to "Open", "#{request.base_url}#{f.file}", target: '_blank' %></td>
      <td>
        <%= link_to 'Edit', edit_admin_blog_path(f), class: 'btn btn-outline-info' %>
      </td>
    </tr>
  <% end %>
  </tbody>
</table>

<%= paginate @blogs%>

app/views/admin/blogs/new.html.erb
<div class="jumbotron">
  <h1 class="display-4">New Blog</h1>
</div>

<div class="row">
  <div class="col">
    <%= render partial: 'admin/blogs/form' %>
  </div>
  <div class="col"></div>
  <div class="col"></div>
</div>

app/views/admin/shared/_alerts.html.erb
<% if flash[:success].present? %>
  <div class="alert alert-success alert-dismissible fade show" role="alert">
    <%= flash[:success] %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"><span aria-hidden="true"></span></button>
  </div>
<%- end %>

<% if flash[:info].present? %>
  <div class="alert alert-info alert-dismissible fade show" role="alert">
    <%= flash[:info] %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"><span aria-hidden="true"></span></button>
  </div>
<%- end %>

<% if flash[:warning].present? %>
  <div class="alert alert-warning alert-dismissible fade show" role="alert">
    <%= flash[:warning] %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"><span aria-hidden="true"></span></button>
  </div>
<%- end %>

<% if flash[:error].present? %>
  <div class="alert alert-danger alert-dismissible fade show" role="alert">
    <%= flash[:error] %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"><span aria-hidden="true"></span></button>
  </div>
<%- end %>

app/views/admin/shared/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <a class="navbar-brand" href="<%= admin_dashboard_path %>">
      Ekanek
    </a>
    <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
      <div class="navbar-nav">
        <div class="d-flex">
          <% if current_user.present? %>
            <%= button_to 'Sign out', admin_logout_path, method: :delete, class: "btn btn-sm btn-outline-danger" %>
          <% else %>
            <%= link_to 'SignIn', admin_login_path, method: :get, class: "nav-link " %>
            <%= link_to 'SignUp', admin_register_path, method: :get, class: "nav-link " %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</nav>

app/views/admin/shared/_sidebar.html.erb
<div class="list-group" id="list-tab" role="tablist">
  <% if current_user %>
    <a class="list-group-item list-group-item-action" id="list-dashboard-list" data-toggle="list" href="<%= admin_dashboard_path %>" role="tab" aria-controls="home">Dashboard</a>
    <a class="list-group-item list-group-item-action" id="list-app-versions-list" data-toggle="list" href="<%= admin_blogs_path %>" role="tab" aria-controls="app-versions">Blogs</a>
  <% else %>
    <!--  do nothing-->
  <% end %>
</div>

app/views/admin/welcome/dashboard.html.erb
<div class="row">
  <div class="col"></div>
  <div class="col">
    <h2 style="padding-top: 30%">Dashboard</h2>
  </div>
  <div class="col"></div>
</div>

app/views/kaminari-default/_first_page.html.erb
<%# Link to the "First" page
  - available local variables
    url:           url to the first page
    current_page:  a page object for the currently displayed page
    total_pages:   total number of pages
    per_page:      number of items to fetch per page
    remote:        data-remote
-%>
<span class="first">
  <%= link_to_unless current_page.first?, t('views.pagination.first').html_safe, url, remote: remote %>
</span>

app/views/kaminari-default/_gap.html.erb
<%# Non-link tag that stands for skipped pages...
  - available local variables
    current_page:  a page object for the currently displayed page
    total_pages:   total number of pages
    per_page:      number of items to fetch per page
    remote:        data-remote
-%>
<span class="page gap"><%= t('views.pagination.truncate').html_safe %></span>

app/views/kaminari-default/_last_page.html.erb
<%# Link to the "Last" page
  - available local variables
    url:           url to the last page
    current_page:  a page object for the currently displayed page
    total_pages:   total number of pages
    per_page:      number of items to fetch per page
    remote:        data-remote
-%>
<span class="last">
  <%= link_to_unless current_page.last?, t('views.pagination.last').html_safe, url, remote: remote %>
</span>

app/views/kaminari-default/_next_page.html.erb
<%# Link to the "Next" page
  - available local variables
    url:           url to the next page
    current_page:  a page object for the currently displayed page
    total_pages:   total number of pages
    per_page:      number of items to fetch per page
    remote:        data-remote
-%>
<span class="next">
  <%= link_to_unless current_page.last?, t('views.pagination.next').html_safe, url, rel: 'next', remote: remote %>
</span>

app/views/kaminari-default/_page.html.erb
<%# Link showing page number
  - available local variables
    page:          a page object for "this" page
    url:           url to this page
    current_page:  a page object for the currently displayed page
    total_pages:   total number of pages
    per_page:      number of items to fetch per page
    remote:        data-remote
-%>
<span class="page<%= ' current' if page.current? %>">
  <%= link_to_unless page.current?, page, url, {remote: remote, rel: page.rel} %>
</span>

app/views/kaminari-default/_paginator.html.erb
<%# The container tag
  - available local variables
    current_page:  a page object for the currently displayed page
    total_pages:   total number of pages
    per_page:      number of items to fetch per page
    remote:        data-remote
    paginator:     the paginator that renders the pagination tags inside
-%>
<%= paginator.render do -%>
  <nav class="pagination" role="navigation" aria-label="pager">
    <%= first_page_tag unless current_page.first? %>
    <%= prev_page_tag unless current_page.first? %>
    <% each_page do |page| -%>
      <% if page.display_tag? -%>
        <%= page_tag page %>
      <% elsif !page.was_truncated? -%>
        <%= gap_tag %>
      <% end -%>
    <% end -%>
    <% unless current_page.out_of_range? %>
      <%= next_page_tag unless current_page.last? %>
      <%= last_page_tag unless current_page.last? %>
    <% end %>
  </nav>
<% end -%>

app/views/kaminari-default/_prev_page.html.erb
<%# Link to the "Previous" page
  - available local variables
    url:           url to the previous page
    current_page:  a page object for the currently displayed page
    total_pages:   total number of pages
    per_page:      number of items to fetch per page
    remote:        data-remote
-%>
<span class="prev">
  <%= link_to_unless current_page.first?, t('views.pagination.previous').html_safe, url, rel: 'prev', remote: remote %>
</span>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>AdminPanel</title>
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  <script
    src="https://code.jquery.com/jquery-3.6.0.min.js"
    integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4="
    crossorigin="anonymous"></script>
</head>

<body>
<div class="container-fluid">
  <%= render partial: 'admin/shared/header' %>
  <% if current_user.present? %>
    <div class="row">
      <div class="col-2">
        <%= render partial: 'admin/shared/sidebar' %>
      </div>
      <div class="col-10">
        <%= render partial: 'admin/shared/alerts' %>
        <%= yield %>
      </div>
    </div>
  <% else %>
    <div class="row">
      <div class="col">
        <%= render partial: 'admin/shared/alerts' %>
        <%= yield %>
      </div>
    </div>
  <% end %>

</div>
<script type="text/javascript" charset="utf-8">
    $(document).ready(function(){
        setTimeout(function(){
            $('.alert').fadeOut('slow');
        }, 5000);
    });
</script>

</body>
</html>

app/views/welcome/index.html.erb
<div class="row">
  <div class="col"></div>
  <div class="col text-center">
    <h4 style="padding-top: 40%">Welcome to Admin panel</h4>
    <p>Please click sign in button for login</p>
  </div>
  <div class="col"></div>
</div>